### ISSUE TITLE
docker-laravel/infra/docker/nginx/default.confの設定変更が反映されない

### ISSUE THREAD

**Issue by ohkaito** [ucan-lab/docker-laravel#138]
はじめまして。私は現在、Laravelを用いて画像ファイルを管理するアプリを作成しています。
NGINXの初期設定では1MB以上のファイルを送信することができません。このままだとHTMLのフォームから画像をアップロードするには都合が悪いので、アップロードできるファイルサイズの上限が10MBになるように、NGINXのdefault.confを変更しました。

```
server {
    # この1行を追加
    client_max_body_size 10M;
    ...
}
```

しかしながら、NGINXを再起動し、加えて念のために`artisan config:cache`を実行しても、ファイルサイズの上限がデフォルト値の1MBから変わっていないようです。
NGINXの再起動がうまく行っていないのかと思い、様々な方法（以下を参照ください）を試したものの、やはり設定が適用されず困っております。
お忙しいところ恐れ入りますが、何か解決策があれば何卒よろしく御願い致します。

```
# 方法1：コマンド
docker kill --signal=SIGHUP docker-laravel_web_1

# 方法1：ログ
2021/07/03 15:34:26 [notice] 1#1: signal 17 (SIGCHLD) received from 70
2021/07/03 15:34:26 [notice] 1#1: worker process 70 exited with code 0
2021/07/03 15:34:26 [notice] 1#1: signal 29 (SIGIO) received
2021/07/03 15:34:26 [notice] 1#1: signal 17 (SIGCHLD) received from 69
2021/07/03 15:34:26 [notice] 1#1: worker process 68 exited with code 0
2021/07/03 15:34:26 [notice] 1#1: worker process 69 exited with code 0
2021/07/03 15:34:26 [notice] 1#1: worker process 71 exited with code 0
2021/07/03 15:34:26 [notice] 1#1: signal 29 (SIGIO) received
2021/07/03 15:34:26 [notice] 1#1: signal 17 (SIGCHLD) received from 68

# 方法2：コマンド
docker exec docker-laravel_web_1 nginx -s reload

# 方法2：ログ
2021/07/03 15:36:55 [notice] 76#76: signal process started
```

**Comment by ucan-lab** [comment]
@ohkaito `infra/docker/nginx/default.conf`を変更した場合ですが、Dockerイメージの再作成が必要です。

```
$ docker compose down
$ docker compose build web
$ docker compose up -d
```

confファイルはDockerfile内でコピーしています。
https://github.com/ucan-lab/docker-laravel/blob/main/infra/docker/nginx/Dockerfile#L18

**Comment by ohkaito** [comment]
> @ohkaito `infra/docker/nginx/default.conf`を変更した場合ですが、Dockerイメージの再作成が必要です。
> 
> ```
> $ docker compose down
> $ docker compose build web
> $ docker compose up -d
> ```
> 
> confファイルはDockerfile内でコピーしています。
> https://github.com/ucan-lab/docker-laravel/blob/main/infra/docker/nginx/Dockerfile#L18

上記のコマンドで無事、変更が反映されました。
ご対応いただきありがとうございました！
