### ISSUE TITLE
Is ssl setup possible with this package ?

### ISSUE THREAD

**Issue by wcaaan** [ucan-lab/docker-laravel#147]

**Comment by mmaaarten** [comment]
Im searching for it as well! if someone has a answer please comment, i want to make 2 pem files with lets encrypt for a production

**Comment by ucan-lab** [comment]
Hi, @wcaaan @mmaaarten 

Thank you.
I added it to the Wiki.
https://github.com/ucan-lab/docker-laravel/wiki/Setup-Local-SSL
