### ISSUE TITLE
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: ./src

### ISSUE THREAD

**Issue by firecentaur** [ucan-lab/docker-laravel#197]
Hi there, I am using this on popOs 22.04, and it doesn't seem to work.

I get this error when I run "make up"

Error response from daemon: invalid mount config for type "bind": bind source path does not exist: ./src
make: *** [Makefile:2: up] Error 1

**Comment by ucan-lab** [comment]
@firecentaur Thank you for your comment.
Execute the following command when creating the project for the first time.

```
$ make create-project
```

https://github.com/ucan-lab/docker-laravel/blob/main/Makefile#L7-L15

The Laravel project will be installed under `./src`.

**Comment by M-Catch** [comment]
> Hi there, I am using this on popOs 22.04, and it doesn't seem to work.
> 
> I get this error when I run "make up"
> 
> Error response from daemon: invalid mount config for type "bind": bind source path does not exist: ./src make: *** [Makefile:2: up] Error 1

same here

**Comment by firecentaur** [comment]
Thanks it now works

**Comment by firecentaur** [comment]
> > Hi there, I am using this on popOs 22.04, and it doesn't seem to work.
> > I get this error when I run "make up"
> > Error response from daemon: invalid mount config for type "bind": bind source path does not exist: ./src make: *** [Makefile:2: up] Error 1
> 
> same here

Hi @[M-Catch](https://github.com/M-Catch), What I did was remove everything and git clone again into a new folder.
Instead of running "make up", run "make create-project"
