### ISSUE TITLE
 Package 'libicu-dev' has no installation candidate

### ISSUE THREAD

**Issue by shahidkarimi** [ucan-lab/docker-laravel#229]
Ubuntu 22.04

Issue: ` Package 'libicu-dev' has no installation candidate`

**Comment by ucan-lab** [comment]
このテンプレートはUbuntuではなくDebianを利用しています。
また、libicu-dev パッケージはここでインストールしています。

https://github.com/ucan-lab/docker-laravel/blob/main/infra/docker/php/Dockerfile#L23

最新のCIでもビルドは落ちていないようです。

https://github.com/ucan-lab/docker-laravel/actions/runs/5570840754

libicu-dev がインストール済みであることも確認しました。

```
$ docker compose app bash
$ dpkg --get-selections | grep libicu-dev
libicu-dev:amd64				install
```

It seems that there is no particular problem, so I will close it.
Please re-open if you have any problems.
