### ISSUE TITLE
feat: add ElasticSearch container

### ISSUE THREAD

**Issue by tarunama** [ucan-lab/docker-laravel#25]
### summary
ElasticSearchのオプションもあったら素敵かな、と。
方針にそぐわないならcloseしちゃってください。

### refs
https://qiita.com/sola-msr/items/64d57d3970b715c795f5

**Comment by ucan-lab** [comment]
悩んだんですけど、やっぱり最低限のコンテナだけ用意したいなと考えてます。
ElasticSearchのコンテナだけでなく、redisとmailのコンテナも削除してwikiとかに追加方法を書くくらいにしようかな〜と思ってます。

**Comment by tarunama** [comment]
ミニマムな思想なんですね！
良いと思います！
