### ISSUE TITLE
Getting permission denied when I try to change any files in the src folder

### ISSUE THREAD

**Issue by nanotexnolagiya** [ucan-lab/docker-laravel#258]
Initialized project with
```
make create-project
```
After that if I try change any files I'm getting error that I don't have a permission to change file
Docker version 26.0.0
OS: Ubuntu 22.04

**Comment by nanotexnolagiya** [comment]
As I see composer creating files with root user.

**Comment by ucan-lab** [comment]
Will using Rootless mode solve the problem?

https://docs.docker.com/engine/security/rootless

**Comment by ucan-lab** [comment]
@nanotexnolagiya
I created a general user inside the container so that I could map the UID and GID of the Linux user on the host side.
Please try it.
