### ISSUE TITLE
URL query strings not working

### ISSUE THREAD

**Issue by ueda222koban** [ucan-lab/docker-laravel#26]
環境構築に利用させて頂いてます。ありがとうございます。
利用していたところ、Laravel側でURLクエリが取得できませんでした。

https://github.com/ucan-lab/docker-laravel/blob/master/infrastructure/docker/nginx/default.conf#L13

↑ 以下に変更すればうまく動きましたー
 `try_files $uri $uri/ /index.php?$query_string`

**Comment by ucan-lab** [comment]
おや...？ おかしいですね🤔
@ueda222koban ご報告ありがとうございます🥰 確認してみます！

一応公式設定のままのはずなんですけどね...
https://readouble.com/laravel/7.x/ja/deployment.html

**Comment by ucan-lab** [comment]
@ueda222koban ちなみにどういったクエリパラメータ送ったのか教えてもらえると助かります！

**Comment by ucan-lab** [comment]
@ueda222koban 簡単に下記のコードを仕込んで見たんですけど、クエリパラメータ取得できました...

```
Route::get('/', function (Request $request) {
    dump($request->all());

    return view('welcome');
});
```

http://127.0.0.1/?foo=bar

<img width="720" alt="スクリーンショット 2020-05-14 0 05 09" src="https://user-images.githubusercontent.com/35098175/81830153-b09d4d80-9576-11ea-9575-b5a37c0c62b0.png">

**Comment by ueda222koban** [comment]
あれれ。
> ちなみにどういったクエリパラメータ送ったのか教えてもらえると助かります！

普通に `?page=1 `  とかだったんですけどね。。。

あまり詳しくないので申し訳ないでのすが
https://github.com/ucan-lab/docker-laravel/blob/master/infrastructure/docker/nginx/default.conf#L13
↑ここの箇所で
try_files $uri $uri/ /index.php `?` $query_string; 
? がないのが原因と思ったんですが。。

**Comment by ucan-lab** [comment]
あまり関係ない気がしてます...！
nginx の access.log にどんな値が入ってきているのか知りたいですね。
ちゃんとリクエストを送れてなかったとかあるかもです。

あと問題を再現させる簡単な手順やコードを共有してもらえたらありがたいです🙏

**Comment by ueda222koban** [comment]
@ucan-lab 
失礼しました。。先ほど確認したら、うまく取得できました。。
うまくリクエストできてなかったかもしれません。お騒がせしました。

**Comment by ucan-lab** [comment]
@ueda222koban ご報告ありがとうございます！
解決できたようですので、こちらのイシューはクローズしちゃいます！

**Comment by ucan-lab** [comment]
@ueda222koban すみません...色々やってたら再現しました。
よくよくみたら公式 `?` 付いてましたね... 公式に合わせたいと思います。
