### ISSUE TITLE
create Project以外で外部プロジェクトを取り込もうとすると失敗する

### ISSUE THREAD

**Issue by SuguruOoki** [ucan-lab/docker-laravel#28]
# 概要

既存のプロジェクトで、docker-laravelを使用しようとすると、
make installでエラーが発生する。

# 気になる点

docker-compose up --build → make install
これは想定したコマンドの流れかどうかが気になります。
もし考慮漏れなら、プルリク出そうかと思ってます！

# 実行した内容

1. srcにLaravelのプロジェクトの中身を配置
![スクリーンショット 2019-11-01 15 44 18](https://user-images.githubusercontent.com/16362021/68007294-7cd79600-fcbe-11e9-99c3-6442af71d4de.png)
2. 

```
docker-compose up -d --build
make install
```
上記コマンドの後に、エラーが発生

![スクリーンショット 2019-11-01 15 43 41](https://user-images.githubusercontent.com/16362021/68007509-26b72280-fcbf-11e9-8708-10ec2327763d.png)
![スクリーンショット 2019-11-01 15 43 49](https://user-images.githubusercontent.com/16362021/68007510-274fb900-fcbf-11e9-8da9-6bbed78cdbf2.png)

**Comment by ucan-lab** [comment]
@SuguruOoki [PhpSpreadsheet](https://github.com/PHPOffice/PhpSpreadsheet) ライブラリのインストール時に PHPの拡張モジュール [GD](https://www.php.net/manual/ja/book.image.php) が求められています。

phpのDockerファイルにgdライブラリを追加して再ビルドしてお試しください！

**Comment by ucan-lab** [comment]
@SuguruOoki こちらのIssueはクローズします。問題ありましたらまたオープンしてください。
