### ISSUE TITLE
phpのDockerfileについてです。

### ISSUE THREAD

**Issue by hs745** [ucan-lab/docker-laravel#77]
すみません。PHPの初心者で学習中の者です。こちらのqiitaで大変勉強になりいつも有難う御座います。

**ただ今貴方様のこちらのDocker-laravelのファイルを参考にして独学でPHPを勉強しようと, macにphp7.4-fpm-buster+nginx+mysql8+phpmyadmin/phpmyadminで構築して”いちばんやさしいPHPの教本”を勉強しました。**
他の目的に近い参考にしたサイトです。
https://php-archive.net/php/docker-php-environment/
https://qiita.com/nemui_/items/f911be7ffa4f29293fd5, etc..

**殆どのサイト通りは全く構築出来ませんでしたが貴方様のDocker-laravelのphpの設定Dockerfileで構築出来ました。深く感謝したします。**

前書き長く申し訳ありません。以前数週間前の貴方様のphpの設定ファイルのDockerfileの記述で、

PHP のDockerfile構成

```
FROM php:7.4-fpm-buster

SHELL ["/bin/bash", "-oeux", "pipefail", "-c"]
ENV TZ=UTC \
    # locale
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8 \
    # composer environment
    COMPOSER_ALLOW_SUPERUSER=1 \
    COMPOSER_HOME=/composer 

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN apt-get update && \
    apt-get -y install git libicu-dev libonig-dev libzip-dev unzip locales && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    locale-gen en_US.UTF-8 && \
    localedef -f UTF-8 -i en_US en_US.UTF-8 && \
    mkdir /var/run/php-fpm && \
    mkdir(--こちらに書いてあった記述を教えて下さい--)
    docker-php-ext-install intl pdo_mysql mbstring zip bcmath && \
    composer config -g process-timeout 3600 && \
    composer config -g repos.packagist composer https://packagist.jp && \
    composer global require hirak/prestissimo

COPY php.ini /usr/local/etc/php/

```

**以前に 
<code>
`mkdir /var/run/php-fpm && \`
</code>

の下にもう一つ 

<code>
`mkdir ~~`
</code>

の記述で稼動できました。**
こちらの記述を覚えていらっしゃいますか？？お忙しいところ恐れ入りますが何卒よろしく御願い致します。m(_ _)m
佐藤秀人

**Comment by ucan-lab** [comment]
@hs745 ご質問ありがとうございます！

> こちらの記述を覚えていらっしゃいますか？？

そこの記述は `mkdir /var/log/php && \` ですね。

https://github.com/ucan-lab/docker-laravel/blame/master/infrastructure/docker/php/Dockerfile
https://github.com/ucan-lab/docker-laravel/pull/2/files#diff-2195b66e4dde148762c4d0b34462d615R35

以前は `php.ini` で下記の設定にしていました。

```
error_log = /var/log/php/php-error.log
```

現在では標準エラー出力に設定してるので、ログディレクトリの作成が不要になりました。

```
error_log = /dev/stderr
```

**Comment by hs745** [comment]
助けて頂き誠に感謝致します。このご恩は一人前になった時に必ず返します。
お忙しい中誠に有難う御座いました!! m(_ _)m
